### PR TITLE
Add expiry and user quotas

### PR DESCRIPTION
**Pull request by chaotix-**
Expiry is controlled by 'expire_interval' and 'expire_maxage' in the config file.

'expire_interval' sets how often old files should be expired (in
    seconds). A '0' (or not setting the entry at all) disables expiry.

'expire_maxage' sets the max age in seconds before files get expired.

'user_quota' sets the maximum space in bytes that a user might use.
    Uploads that will exceed this limit will be refused.
    A '0' (or not setting the entry at all) disables user quotas.

Please note that the line "from threading import Thread" that was removed in pull request #22 because it was not necessary is needed for this PR. 

Expiry also deletes empty directories (as opposed to a simple cron job as in PR #20) to keeps things tidy.

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Hi

thanks for the contribution. For the 'official' 'build-in' expire mechanism I would rather see something that just keeps the last x MiB of every user independent of file age.

**Comment by chaotix-** [comment]
I thought about that but I saw some problems and i didn't know if solving them was worth the IO or RAM cost.

1. Expiry has to be more or less instantaneous. If there is an expiry run only every x hours a user may exceed the quote by a great margin. If only the files exceeding the quote are deleted there will almost always be an expiry after a user filled up his quota for the first time. So with every upload there needs to be a complete directory scan of the users files or the metadata of all files for all users must be kept in memory at all times. I don't know if this is wise for scalability reasons. An alternative would be to store the metadata in a database. But that would add maybe unwanted complexity and dependencies in setting this up.

2. If files only get deleted when the user quota is exceeded old stuff of inactive users will hang around indefinately (although a seperate expiry mechanism like the one in this PR would solve this problem).

So what do you propose? Let a user exceed the quota for x hours, keep all metadata in memory or store it in a database?

**Comment by chaotix-** [comment]
I thought about it some more... What about some middle ground?

Add a `user_quota_soft` and a `user_quota_hard` config option. Everything above the soft quota will be deleted by the expiry run (starting with the oldest files). But uploads are stopped after exceeding the hard quota, so there will always be space to upload something. With this approach there is no need to keep track of all metadata all the time as the expiry does not need to be instantaneous. You could even see this as a feature to protect the server from excessive uploads because a user cannot upload more than hard - soft quota per `expire_interval`.

I think combined with `expire_maxage` this is not a bad solution. Would you be willing to merge something like this?

**Comment by iNPUTmice** [comment]
Hi @chaotix- 

what you said about ```user_quota_soft``` and ```user_quota_hard``` sounds very reasonable to me. Let's implement this.

But let's keep the final expire out of this and rather rely on solutions like the simple cron script in the contrib directory or individual solutions that work along side your normal 'delete stale accounts' mechanisms. Having the 'final delete' done external also forces the internal counting/quota mechanisms to deal with external deletes which sounds like it should be capable of that anyway.

**Comment by chaotix-** [comment]
What do you mean with "keep the final expire out"? Do you mean to not implement an expiration based on file age? Are you sure this is the right way to go? All the work (traversing all the directories and stating every file) has to be done anyway. It's just two lines of code to delete anything older than x seconds/days/months/whatever. And it's easily disabled by the admin by setting `expire_maxage` to `0`. Using a cron job just adds the IO cost of traversing and stating all the files again.

**Comment by iNPUTmice** [comment]
Ok fair enough. Reading your code right now. Since you are modifying the quata[user] value from two different threads shouldn't you be locking on that somehow?

**Comment by chaotix-** [comment]
I thought about locking, but I don't think it's critical.

- ```quotas[sender] = quota``` in ```expire()``` is atomic.
- ```quotas.setdefault(sender_hash, 0)``` in ```request_upload_slot()``` and ```do_PUT()``` is not (I think). Worst case scenario the user does not get the freed space credited until the next expiry run. But I think the chances of this happening are smaller than a power outage as ```quotas[sender] = quota``` has to be not only just when a user uploads something but between ```quotas.setdefault()``` getting the old value and storing the new one just while an ```expire_run()``` (that happens every couple of hours) is finished just with this user and sets his new quota.
- ```quotas[sender_hash] += databytes``` in ```do_PUT()``` is not atomic. Again chances of this happening are next to null.

As I considered the chances of an incident really, really, really small and the consequences neglegible as no data corruption is happening only the user will not get credit for freed space and this will self-correct at the next expiry run, I didn't think the runtime cost and complexity of locking were worth it. But if you think it necessary I can add the locking mechanism.

**Comment by chaotix-** [comment]
Just looked it up: ```setdefault()``` is atomic (since a bugfix in 2012 https://bugs.python.org/issue13521). So this just leaves ```quotas[sender_hash] += databytes```.

**Comment by iNPUTmice** [comment]
Ok thanks. Can you squash this for me?

**Comment by chaotix-** [comment]
> Can you squash this for me?

What do you mean? Add a locking mechanism for access to the quotas dict? I can look into it but it might be a day or two before I get around to it.

There is also another small possibility that a user might occupy a little bit more space than set by ```user_quota_hard```:
1. Expiry run starts for user x and collects size stats
2. User x starts uploading a file
3. Expiry run for user x finishes, but the collected size stats do not contain the part the user has uploaded since expiry started.

This way the user might exceed ```user_quota_hard``` by the amount of data s/he has uploaded during the expiry run. As an expiry run for a single user should not take that long I don't think this is a problem as this should not be more than a couple of kB. But maybe someone running a server on a 10GBit/s connection and a Class 2 SD-card as storage would see it otherwise. :-)

Do you have a problem with this? Especially to prevent this uploads for a user must be blocked during the expiry of his files. In turn this might lead to all users being blocked under adverse conditions during an expiry run (or there needs to be a lock for every single user which I think is complete overkill).

**Comment by iNPUTmice** [comment]
No sorry misunderstanding. I was trying to say if you could squash those commits for me. Making all the commit into one.

**Comment by chaotix-** [comment]
OK. I hope I did it right. Never squashed anything before. :-)

**Pull request merged**
